### ISSUE TITLE
consider about add other based on graph method like hnsw?

### ISSUE THREAD

**Issue by alexw994** [ankane/pgvector#10]
like title

**Comment by ankane** [comment]
Hey @alexw994, thanks for the suggestion. Adding and supporting new index types is a good amount of work, so I'd like to be selective about it. I currently think product quantization is a better fit for the library than graph-based methods, and I believe it can achieve state-of-the-art performance (like [ScaNN](https://ai.googleblog.com/2020/07/announcing-scann-efficient-vector.html)).
