### ISSUE TITLE
16bit float support

### ISSUE THREAD

**Issue by mikeizbicki** [ankane/pgvector#14]
I'm using this library on a rather large set of vectors (>10^9), and so I'm considering forking the code so that the internal storage format is 16bit floats rather than 32bit floats.  I don't really care about any potential speedup from using half precision floats as I imagine even under ideal hardware this will be negligible, I'm really just interested in space savings.

Ideally, I'd figure out a way to do some macro magic in order to have all of your existing index code work on both a 16bit and 32bit type (and possibly a 64bit type while I'm at it), but before I get started on this, I'm wondering if you've thought about this at all?  And if you'd be open to a pull request that does this even if it makes the existing code quite a bit more complicated?

**Comment by ankane** [comment]
Hey @mikeizbicki, it's an interesting idea for large datasets (and the macro approach makes sense). I think it'll likely add more complexity than I'd like to support right now, but let me know if you have any luck with it.

**Comment by tfriedel** [comment]
@mikeizbicki 
Did you implement this in your fork? Space usage is also a concern for me. FAISS is very good at this, also with the quantization to uint8. Would love to see this here as an option as well.
