### ISSUE TITLE
How to set threshold for search

### ISSUE THREAD

**Issue by huuthieu** [ankane/pgvector#16]
Thanks for your awesome project. I want to query vector using L2 distance, which is larger than given threshold. How can I do that ?

**Comment by ankane** [comment]
Hey @huuthieu, you can do:

```sql
SELECT * FROM table WHERE column <-> '[1,2,3]' > 100;
```

or

```sql
SELECT * FROM table WHERE l2_distance(column, '[1,2,3]') > 100;
```

**Comment by huuthieu** [comment]
Hi @ankane , your answer helped me a lot.
I met another issue when I used psycopg2 that for the same query, most of the time it returns data but sometimes it returns empty.
