### ISSUE TITLE
Index usage in queries

### ISSUE THREAD

**Issue by siarheidevel** [ankane/pgvector#19]
Hello. I created table

create table garment_vector(
    garment_id int primary key,
    vecdata vector(192)
);

CREATE INDEX  l2_vector_index ON  garment_vector 
USING ivfflat (vecdata vector_l2_ops) WITH (lists = 1000);

It has 350000 rows

In this query postgres uses ivfflat index
explain analyze
select *
from garment_vector v1
order by v1.vecdata <-> '[-0.047943115234375,0.02069091796875,-0.04364013671875, .... ,0.04705810546875]'  limit 10

Limit  (cost=142.46..146.59 rows=10 width=788) (actual time=1.206..1.231 rows=10 loops=1)
  ->  Index Scan using l2_vector_index on garment_vector v1  (cost=142.46..142075.46 rows=344080 width=788) (actual time=1.205..1.229 rows=10 loops=1)
        Order By: (vecdata <-> '[-0.047943115234375,0.02069091796875,...0.04705810546875]'::vector)
Planning Time: 0.439 ms
Execution Time: 1.272 ms

The same with
explain analyze
select *
from garment_vector v1
order by v1.vecdata <-> (select v2.vecdata from garment_vector v2 where v2.garment_id=1)  limit 10

Limit  (cost=153.53..157.66 rows=10 width=788) (actual time=1.053..1.076 rows=10 loops=1)
  InitPlan 1 (returns $0)
    ->  Index Scan using garment_vector_pkey on garment_vector v2  (cost=0.42..8.44 rows=1 width=776) (actual time=0.008..0.009 rows=1 loops=1)
          Index Cond: (garment_id = 1)
  ->  Index Scan using l2_vector_index on garment_vector v1  (cost=145.09..144812.97 rows=350710 width=788) (actual time=1.052..1.073 rows=10 loops=1)
        Order By: (vecdata <-> $0)
Planning Time: 0.702 ms
Execution Time: 1.110 ms

But in this query, postgres uses sequential scan
explain analyze
select *
from garment_vector v1,
garment_vector v2 
where v2.garment_id=1
order by v1.vecdata <-> v2.vecdata  limit 10

Limit  (cost=51011.72..51011.75 rows=10 width=1568) (actual time=357.449..357.453 rows=10 loops=1)
  ->  Sort  (cost=51011.72..51896.52 rows=353920 width=1568) (actual time=357.448..357.450 rows=10 loops=1)
        Sort Key: ((v1.vecdata <-> v2.vecdata))
        Sort Method: top-N heapsort  Memory: 59kB
        ->  Nested Loop  (cost=0.42..43363.64 rows=353920 width=1568) (actual time=0.031..256.816 rows=353920 loops=1)
              ->  Index Scan using garment_vector_pkey on garment_vector v2  (cost=0.42..8.44 rows=1 width=780) (actual time=0.009..0.011 rows=1 loops=1)
                    Index Cond: (garment_id = 1)
              ->  Seq Scan on garment_vector v1  (cost=0.00..38931.20 rows=353920 width=780) (actual time=0.020..116.430 rows=353920 loops=1)
Planning Time: 0.768 ms
Execution Time: 357.487 ms

How to use index inqueries with join?
 I'm using PostgreSQL 14.0 (Debian 14.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit in Docker container compiled from latest version (0.2) of pgvector

**Comment by ankane** [comment]
Hey @siarheidevel, I'm not sure if it's possible, so I'd recommend using one of the first two queries.

**Comment by parikls** [comment]
@ankane will this ever be possible?
