### ISSUE TITLE
array equals comparison stopped working

### ISSUE THREAD

**Issue by dandiep** [ankane/pgvector#20]
I am having some problems after installing the extension in Postgres 14.

First, array equal comparisons seem to have stopped working. Message:

`HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.`

This is after adding the casts as well. The relevant part of the query is:

`and CAST(word_ids as int[]) = CAST([myvalues] as int[])`

I'm not sure if this is related, but the bigint comparison also seems to have stopped working. When I do a very simple query like this:

`select * from word w where w.signature = 3866747771;`

I get `ERROR:  unrecognized strategy number: 2`

If I provide a shorter number, it appears to work fine.

I apologize I don't have a full test case worked up, but I wanted to see if this rings any bells.

**Comment by ankane** [comment]
Hey @dandiep, I'm having trouble following. Can you put together a repro script?

**Comment by dandiep** [comment]
I'll work on it. Sorry for the bad issue description in the meantime.

**Comment by dandiep** [comment]
Apologies for the delay, but this simple test fails for me after installing the extension on PG 14. No other extensions are installed. When I remove the vector column and the extension, it works fine.

-- Table Definition ----------------------------------------------

CREATE TABLE test_array (
    id SERIAL PRIMARY KEY,
    arraycol integer[],
    vectorcol vector(3)
);

-- This select fails with the vector extension installed
select * from test_array
where arraycol = ARRAY[1,2,3];

**Comment by ankane** [comment]
Thanks @dandiep! Fixed the issue in the commit above and will push a new release shortly.

**Comment by dandiep** [comment]
Sweet - thanks for the quick turnaround. I'll give it a whirl later this week.
