### ISSUE TITLE
Dockerize pgvector

### ISSUE THREAD

**Issue by calufa** [ankane/pgvector#5]
Hi @ankane,

First of all, thanks for open-sourcing this project.  

I have been testing a few use cases and the results are very promising!

I wanted to share the docker setup I'm using in case other devs want to run `pgvector` without having to compile or deal with dependencies. The resulting Docker image supports all the features as in https://hub.docker.com/_/postgres, as it extends directly from it.

Here is the PR https://github.com/ankane/pgvector/pull/4

I'm curious:
- have you taken perf benchmarks?
- any important limitations (scalability, sharding, vector size)?

Thanks!

**Comment by ankane** [comment]
Hey @calufa, thanks again for the PR. For the questions:

1. I put together [a script](https://github.com/erikbern/ann-benchmarks/compare/master...ankane:pgvector) for ann-benchmarks, but need to spend a bit more time on it.

2. See [this comment](https://github.com/ankane/pgvector/issues/2#issuecomment-825295605) for limitations. Also, vectors are limited to 1024 dimensions.
