### ISSUE TITLE
Installing pgvector on a cloud pgsql instancw

### ISSUE THREAD

**Issue by shashi-netra** [ankane/pgvector#6]
The instructions mention:

```
git clone --branch v0.1.2 https://github.com/ankane/pgvector.git
cd pgvector
make
make install # may need sudo
```

How do I do it for a pg instance on Google cloud? Is it possible?

**Comment by ankane** [comment]
Hey @shashi-netra, only certain extensions are supported on Google Cloud SQL. You can request a [new extension here](https://cloud.google.com/sql/docs/postgres/extensions#requesting-support-for-a-new-extension). Please share the link if you do.

**Comment by ankane** [comment]
Thanks @emirpasic, there's also a request here: https://issuetracker.google.com/issues/265172065

**Comment by emirpasic** [comment]
My bad, I will close the duplicate I've just created. Cheers
